/// Pool of 50 ancient Greek city and region names for auto-assignment.
/// When a new player signs up, the handle_new_user DB trigger picks
/// a random name from a subset of this list for their starting city.
class CityNameConstants {
  CityNameConstants._();

  static const List<String> names = [
    'Sparta',
    'Athens',
    'Corinth',
    'Argos',
    'Thebes',
    'Delphi',
    'Rhodes',
    'Olympia',
    'Mycenae',
    'Epidaurus',
    'Megara',
    'Tegea',
    'Sicyon',
    'Phlius',
    'Mantinea',
    'Elis',
    'Ithaca',
    'Pylos',
    'Tiryns',
    'Nafplio',
    'Knossos',
    'Miletos',
    'Ephesos',
    'Pergamon',
    'Halicarnassus',
    'Byzantion',
    'Thessaloniki',
    'Larissa',
    'Patras',
    'Chalkis',
    'Eretria',
    'Naxos',
    'Samos',
    'Lesbos',
    'Chios',
    'Delos',
    'Thera',
    'Kerkyra',
    'Zakynthos',
    'Lefkada',
    'Messene',
    'Troezen',
    'Hermione',
    'Asine',
    'Lerna',
    'Nemea',
    'Stymphalos',
    'Pheneos',
    'Kleitor',
    'Orchomenos',
  ];
}
